name: Production DNS Deploy

on:
  pull_request:
    branches:
      - main
    paths:
      - dns_records.yml

  push:
    branches:
      - main
    paths:
      - dns_records.yml

jobs:

  validate:
    name: DNS Validation
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Validation Only
        run: |
          cd ansible
          ansible-playbook -i inventory.ini deploy-dns.yml --check

  deploy:
    name: Deploy to Production
    runs-on: self-hosted
    needs: validate
    if: github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run DNS Deployment
        run: |
          cd ansible
          ansible-playbook -i inventory.ini deploy-dns.yml
